-- Generated by Oracle SQL Developer Data Modeler 4.0.3.853
--   at:        2015-03-05 17:55:36 GMT
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g




CREATE TABLE Course
  (
    Course_ID    VARCHAR2 (10) NOT NULL ,
    Course_Name  VARCHAR2 (20) NOT NULL ,
    Course_Mode  VARCHAR2 (4) NOT NULL ,
    Course_SDate DATE NOT NULL ,
    Course_EDate DATE NOT NULL ,
    QName        VARCHAR2 (4) NOT NULL
  ) ;
ALTER TABLE Course ADD CONSTRAINT Course_PK PRIMARY KEY ( Course_ID ) ;

CREATE TABLE Employed
  (
    Emp_Name     VARCHAR2 (20) NOT NULL ,
    Emp_Sal      NUMBER (5) NOT NULL ,
    Emp_Hiredate DATE NOT NULL ,
    Emp_Mode     VARCHAR2 (4) NOT NULL ,
    Emp_Duty     VARCHAR2 (20) NOT NULL ,
    Emp_Unpaid   VARCHAR2 (10) NOT NULL ,
    Emp_Hours    NUMBER (2) NOT NULL ,
    Emp_EstEarn  NUMBER (6) NOT NULL ,
    Emp_Makedo   VARCHAR2 (10) NOT NULL ,
    Emp_Place    VARCHAR2 (20) NOT NULL ,
    Emp_PCode    VARCHAR2 (9) NOT NULL ,
    Emp_Country  VARCHAR2 (20) NOT NULL ,
    Emp_QualReq  NUMBER (2) NOT NULL ,
    Grad_ID      NUMBER (7) NOT NULL
  ) ;

CREATE TABLE Graduate
  (
    Grad_ID        NUMBER (7) NOT NULL ,
    Grad_RECID     NUMBER (5) NOT NULL ,
    Grad_UKPRN     NUMBER (8) NOT NULL ,
    Grad_FName     VARCHAR2 (10) NOT NULL ,
    Grad_SName     VARCHAR2 (10) NOT NULL ,
    Grad_OName     VARCHAR2 (10) ,
    Grad_Email     VARCHAR2 (20) NOT NULL ,
    Grad_DOB       DATE NOT NULL ,
    Grad_Gender    VARCHAR2 (6) NOT NULL ,
    Grad_Phone     NUMBER (12) NOT NULL ,
    Grad_Called    VARCHAR2 (3) NOT NULL ,
    Grad_Call_Back VARCHAR2 (3) NOT NULL ,
    Grad_Timestamp DATE NOT NULL ,
    Grad_Town_City VARCHAR2 (20) NOT NULL ,
    Grad_County    VARCHAR2 (20) NOT NULL ,
    Grad_PostCode  VARCHAR2 (9) NOT NULL ,
    Grad_Address1  VARCHAR2 (20) NOT NULL ,
    Grad_Address2  VARCHAR2 (20) ,
    Grad_Address3  VARCHAR2 (20) ,
    Grad_Address4  VARCHAR2 (20) ,
    Grad_Address5  VARCHAR2 (20) ,
    Grad_Country   VARCHAR2 (10) NOT NULL ,
    Course_ID      VARCHAR2 (10) NOT NULL ,
    Staff_ID       VARCHAR2 (8) NOT NULL ,
    Over_Exp_ID    NUMBER (8) NOT NULL
  ) ;
ALTER TABLE Graduate ADD CONSTRAINT Graduate_PK PRIMARY KEY ( Grad_ID ) ;

CREATE TABLE Over_Exp
  (
    Exp_ID    NUMBER (8) NOT NULL ,
    Exp_Emp   VARCHAR2 (20) NOT NULL ,
    Exp_Study VARCHAR2 (20) NOT NULL ,
    Exp_Self  VARCHAR2 (20) NOT NULL
  ) ;
ALTER TABLE Over_Exp ADD CONSTRAINT Over_Exp_PK PRIMARY KEY ( Exp_ID ) ;

CREATE TABLE Staff
  (
    Staff_ID       VARCHAR2 (8) NOT NULL ,
    Staff_name     VARCHAR2 (10) NOT NULL ,
    Staff_pass     VARCHAR2 (8) NOT NULL ,
    Staff_job      VARCHAR2 (10) NOT NULL ,
    Staff_sal      NUMBER (5) NOT NULL ,
    Staff_hiredate DATE NOT NULL ,
    No_Calls       NUMBER (2) NOT NULL
  ) ;
ALTER TABLE Staff ADD CONSTRAINT Staff_PK PRIMARY KEY ( Staff_ID ) ;

CREATE TABLE Study
  (
    Study_Name          VARCHAR2 (20) NOT NULL ,
    Study_Mode          VARCHAR2 (4) NOT NULL ,
    Study_SDate         DATE NOT NULL ,
    Study_EDate         DATE NOT NULL ,
    Study_Subject       VARCHAR2 (20) NOT NULL ,
    Study_Fund          VARCHAR2 (20) NOT NULL ,
    Study_Qualification VARCHAR2 (4) NOT NULL ,
    Grad_ID             NUMBER (7) NOT NULL
  ) ;

ALTER TABLE Employed ADD CONSTRAINT Employed_Graduate_FK FOREIGN KEY ( Grad_ID ) REFERENCES Graduate ( Grad_ID ) ;

ALTER TABLE Graduate ADD CONSTRAINT Graduate_Course_FK FOREIGN KEY ( Course_ID ) REFERENCES Course ( Course_ID ) ;

ALTER TABLE Graduate ADD CONSTRAINT Graduate_Over_Exp_FK FOREIGN KEY ( Over_Exp_ID ) REFERENCES Over_Exp ( Exp_ID ) ;

ALTER TABLE Graduate ADD CONSTRAINT Graduate_Staff_FK FOREIGN KEY ( Staff_ID ) REFERENCES Staff ( Staff_ID ) ;

ALTER TABLE Study ADD CONSTRAINT Study_Graduate_FK FOREIGN KEY ( Grad_ID ) REFERENCES Graduate ( Grad_ID ) ;


-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             6
-- CREATE INDEX                             0
-- ALTER TABLE                              9
-- CREATE VIEW                              0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
